- name: Test NET cred issue
  hosts: localhost
  gather_facts: true
  # Gather facts must be false or OLD OS will fail, if you need it later then run setup module

  tasks:

  - name: Gather facts for localhost
    ansible.builtin.setup:
    run_once: true
    delegate_to: localhost
    tags: ["inspec_exec"]

  - name: Display all environment variables 
    ansible.builtin.debug:
      msg: "{{ ansible_env }}"
    run_once: true
    delegate_to: localhost

  - name: pause
    pause:
      seconds: 300
