- name: Test NET cred issue
  hosts: localhost
  gather_facts: true

  tasks:

  - name: Gather facts for localhost
    ansible.builtin.setup:
    run_once: true
    delegate_to: localhost

  - name: Display all environment variables
    ansible.builtin.debug:
      msg: "{{ ansible_env }}"
    run_once: true
    delegate_to: localhost

  - name: pause
    pause:
      seconds: 300
